# Generated by Django 5.1.6 on 2025-04-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
